-- =============================================
-- Expand breed_aliases: comprehensive Chinese cat & dog breeds
-- =============================================
-- Purpose:
--   Build the foundation for breed-level long-term data aggregation
--   (e.g. "我家猫最近软便" → cohort analysis by breed). Each entry
--   maps an alias (e.g. "布偶") to a canonical name (e.g. "布偶猫").
--   The existing `normalize_breed()` function and `breed_product_stats`
--   materialized view already aggregate by canonical name, so this
--   migration is the data-side prerequisite.
--
-- Notes:
--   * Idempotent via ON CONFLICT DO NOTHING.
--   * Coverage focuses on breeds popular in mainland China (CFA/TICA
--     recognized + widely bred local cats). Coats/colors ("橘猫",
--     "三花猫", "奶牛猫", "白猫", "黑猫") are kept as canonical since
--     they are the most common forms in the CN user base.
--   * Dog list covers common companion breeds; "中华田园犬" /
--     "土狗" is its own canonical to preserve Chinese cultural context.

INSERT INTO public.breed_aliases (alias, canonical, species) VALUES
  -- ── Cat: popular coat/pattern types in CN ──
  ('中国狸花猫', '中国狸花猫', 'cat'),
  ('狸花猫', '中国狸花猫', 'cat'),
  ('狸花', '中国狸花猫', 'cat'),
  ('dragon li', '中国狸花猫', 'cat'),
  ('li hua', '中国狸花猫', 'cat'),
  ('橘猫', '橘猫', 'cat'),
  ('大橘', '橘猫', 'cat'),
  ('orange tabby', '橘猫', 'cat'),
  ('三花猫', '三花猫', 'cat'),
  ('三花', '三花猫', 'cat'),
  ('calico', '三花猫', 'cat'),
  ('奶牛猫', '奶牛猫', 'cat'),
  ('黑白猫', '奶牛猫', 'cat'),
  ('tuxedo', '奶牛猫', 'cat'),
  ('白猫', '白猫', 'cat'),
  ('纯白猫', '白猫', 'cat'),
  ('黑猫', '黑猫', 'cat'),
  ('纯黑猫', '黑猫', 'cat'),
  ('玳瑁猫', '玳瑁猫', 'cat'),
  ('玳瑁', '玳瑁猫', 'cat'),
  ('tortoiseshell', '玳瑁猫', 'cat'),

  -- ── Cat: popular pure breeds ──
  ('布偶猫', '布偶猫', 'cat'),
  ('布偶', '布偶猫', 'cat'),
  ('ragdoll', '布偶猫', 'cat'),
  ('英国短毛猫', '英国短毛猫', 'cat'),
  ('英短', '英国短毛猫', 'cat'),
  ('蓝猫', '英国短毛猫', 'cat'),
  ('蓝胖子', '英国短毛猫', 'cat'),
  ('british shorthair', '英国短毛猫', 'cat'),
  ('美国短毛猫', '美国短毛猫', 'cat'),
  ('美短', '美国短毛猫', 'cat'),
  ('american shorthair', '美国短毛猫', 'cat'),
  ('暹罗猫', '暹罗猫', 'cat'),
  ('暹罗', '暹罗猫', 'cat'),
  ('siamese', '暹罗猫', 'cat'),
  ('波斯猫', '波斯猫', 'cat'),
  ('波斯', '波斯猫', 'cat'),
  ('persian', '波斯猫', 'cat'),
  ('缅因猫', '缅因猫', 'cat'),
  ('缅因', '缅因猫', 'cat'),
  ('maine coon', '缅因猫', 'cat'),
  ('加菲猫', '加菲猫', 'cat'),
  ('异国短毛猫', '加菲猫', 'cat'),
  ('异短', '加菲猫', 'cat'),
  ('exotic shorthair', '加菲猫', 'cat'),
  ('苏格兰折耳猫', '苏格兰折耳猫', 'cat'),
  ('折耳', '苏格兰折耳猫', 'cat'),
  ('折耳猫', '苏格兰折耳猫', 'cat'),
  ('scottish fold', '苏格兰折耳猫', 'cat'),
  ('美国卷耳猫', '美国卷耳猫', 'cat'),
  ('卷耳', '美国卷耳猫', 'cat'),
  ('american curl', '美国卷耳猫', 'cat'),
  ('俄罗斯蓝猫', '俄罗斯蓝猫', 'cat'),
  ('俄蓝', '俄罗斯蓝猫', 'cat'),
  ('russian blue', '俄罗斯蓝猫', 'cat'),
  ('加拿大无毛猫', '加拿大无毛猫', 'cat'),
  ('斯芬克斯', '加拿大无毛猫', 'cat'),
  ('无毛猫', '加拿大无毛猫', 'cat'),
  ('sphynx', '加拿大无毛猫', 'cat'),
  ('阿比西尼亚猫', '阿比西尼亚猫', 'cat'),
  ('阿比', '阿比西尼亚猫', 'cat'),
  ('abyssinian', '阿比西尼亚猫', 'cat'),
  ('孟买猫', '孟买猫', 'cat'),
  ('bombay', '孟买猫', 'cat'),
  ('伯曼猫', '伯曼猫', 'cat'),
  ('缅甸猫', '缅甸猫', 'cat'),
  ('burmese', '缅甸猫', 'cat'),
  ('土耳其安哥拉猫', '土耳其安哥拉猫', 'cat'),
  ('安哥拉猫', '土耳其安哥拉猫', 'cat'),
  ('turkish angora', '土耳其安哥拉猫', 'cat'),
  ('土耳其梵猫', '土耳其梵猫', 'cat'),
  ('梵猫', '土耳其梵猫', 'cat'),
  ('turkish van', '土耳其梵猫', 'cat'),
  ('挪威森林猫', '挪威森林猫', 'cat'),
  ('挪威森林', '挪威森林猫', 'cat'),
  ('norwegian forest cat', '挪威森林猫', 'cat'),
  ('西伯利亚森林猫', '西伯利亚森林猫', 'cat'),
  ('西伯利亚', '西伯利亚森林猫', 'cat'),
  ('siberian', '西伯利亚森林猫', 'cat'),
  ('孟加拉豹猫', '孟加拉豹猫', 'cat'),
  ('豹猫', '孟加拉豹猫', 'cat'),
  ('bengal', '孟加拉豹猫', 'cat'),
  ('萨凡纳猫', '萨凡纳猫', 'cat'),
  ('薮猫', '萨凡纳猫', 'cat'),
  ('savannah', '萨凡纳猫', 'cat'),
  ('东奇尼猫', '东奇尼猫', 'cat'),
  ('tonkinese', '东奇尼猫', 'cat'),
  ('哈瓦那棕猫', '哈瓦那棕猫', 'cat'),
  ('havana brown', '哈瓦那棕猫', 'cat'),
  ('索马里猫', '索马里猫', 'cat'),
  ('somali', '索马里猫', 'cat'),
  ('巴厘猫', '巴厘猫', 'cat'),
  ('巴厘岛猫', '巴厘猫', 'cat'),
  ('balinese', '巴厘猫', 'cat'),
  ('爪哇猫', '爪哇猫', 'cat'),
  ('javanese', '爪哇猫', 'cat'),
  ('东方短毛猫', '东方短毛猫', 'cat'),
  ('东方短毛', '东方短毛猫', 'cat'),
  ('oriental shorthair', '东方短毛猫', 'cat'),
  ('东方长毛猫', '东方长毛猫', 'cat'),
  ('oriental longhair', '东方长毛猫', 'cat'),
  ('柯尼斯卷毛猫', '柯尼斯卷毛猫', 'cat'),
  ('cornish rex', '柯尼斯卷毛猫', 'cat'),
  ('德文卷毛猫', '德文卷毛猫', 'cat'),
  ('德文', '德文卷毛猫', 'cat'),
  ('devon rex', '德文卷毛猫', 'cat'),
  ('塞尔凯克卷毛猫', '塞尔凯克卷毛猫', 'cat'),
  ('selkirk rex', '塞尔凯克卷毛猫', 'cat'),
  ('美国短尾猫', '美国短尾猫', 'cat'),
  ('american bobtail', '美国短尾猫', 'cat'),
  ('日本短尾猫', '日本短尾猫', 'cat'),
  ('日本截尾猫', '日本短尾猫', 'cat'),
  ('japanese bobtail', '日本短尾猫', 'cat'),
  ('千岛短尾猫', '千岛短尾猫', 'cat'),
  ('kurilian bobtail', '千岛短尾猫', 'cat'),
  ('马恩岛猫', '马恩岛猫', 'cat'),
  ('manx', '马恩岛猫', 'cat'),
  ('褴褛猫', '褴褛猫', 'cat'),
  ('ragamuffin', '褴褛猫', 'cat'),
  ('喜马拉雅猫', '喜马拉雅猫', 'cat'),
  ('重点色波斯猫', '喜马拉雅猫', 'cat'),
  ('himalayan', '喜马拉雅猫', 'cat'),
  ('重点色短毛猫', '重点色短毛猫', 'cat'),
  ('colorpoint shorthair', '重点色短毛猫', 'cat'),
  ('欧洲短毛猫', '欧洲短毛猫', 'cat'),
  ('欧洲短毛', '欧洲短毛猫', 'cat'),
  ('european shorthair', '欧洲短毛猫', 'cat'),

  -- ── Cat: catch-all for mixed / unknown ──
  ('米克斯', '米克斯', 'cat'),
  ('mix', '米克斯', 'cat'),
  ('mixed', '米克斯', 'cat'),
  ('混血猫', '米克斯', 'cat'),
  ('家猫', '米克斯', 'cat'),

  -- ── Dog: Chinese native / local ──
  ('中华田园犬', '中华田园犬', 'dog'),
  ('土狗', '中华田园犬', 'dog'),
  ('大黄', '中华田园犬', 'dog'),
  ('chinese rural dog', '中华田园犬', 'dog'),
  ('松狮犬', '松狮犬', 'dog'),
  ('松狮', '松狮犬', 'dog'),
  ('chow chow', '松狮犬', 'dog'),
  ('藏獒', '藏獒', 'dog'),
  ('tibetan mastiff', '藏獒', 'dog'),
  ('巴哥犬', '巴哥犬', 'dog'),
  ('巴哥', '巴哥犬', 'dog'),
  ('pug', '巴哥犬', 'dog'),
  ('北京犬', '北京犬', 'dog'),
  ('京巴', '北京犬', 'dog'),
  ('pekingese', '北京犬', 'dog'),
  ('西施犬', '西施犬', 'dog'),
  ('西施', '西施犬', 'dog'),
  ('shih tzu', '西施犬', 'dog'),
  ('沙皮犬', '沙皮犬', 'dog'),
  ('沙皮', '沙皮犬', 'dog'),
  ('shar pei', '沙皮犬', 'dog'),
  ('中国冠毛犬', '中国冠毛犬', 'dog'),
  ('冠毛犬', '中国冠毛犬', 'dog'),
  ('chinese crested', '中国冠毛犬', 'dog'),
  ('西藏梗', '西藏梗', 'dog'),
  ('tibetan terrier', '西藏梗', 'dog'),
  ('西藏猎犬', '西藏猎犬', 'dog'),
  ('拉萨犬', '西藏猎犬', 'dog'),
  ('lhasa apso', '西藏猎犬', 'dog'),

  -- ── Dog: popular Japanese / Asian ──
  ('柴犬', '柴犬', 'dog'),
  ('shiba inu', '柴犬', 'dog'),
  ('秋田犬', '秋田犬', 'dog'),
  ('akita', '秋田犬', 'dog'),

  -- ── Dog: popular Western breeds ──
  ('金毛寻回犬', '金毛寻回犬', 'dog'),
  ('金毛', '金毛寻回犬', 'dog'),
  ('golden retriever', '金毛寻回犬', 'dog'),
  ('拉布拉多寻回犬', '拉布拉多寻回犬', 'dog'),
  ('拉布拉多', '拉布拉多寻回犬', 'dog'),
  ('labrador', '拉布拉多寻回犬', 'dog'),
  ('labrador retriever', '拉布拉多寻回犬', 'dog'),
  ('贵宾犬', '贵宾犬', 'dog'),
  ('贵宾', '贵宾犬', 'dog'),
  ('泰迪', '贵宾犬', 'dog'),
  ('poodle', '贵宾犬', 'dog'),
  ('比熊犬', '比熊犬', 'dog'),
  ('比熊', '比熊犬', 'dog'),
  ('bichon frise', '比熊犬', 'dog'),
  ('博美犬', '博美犬', 'dog'),
  ('博美', '博美犬', 'dog'),
  ('pomeranian', '博美犬', 'dog'),
  ('威尔士柯基犬', '威尔士柯基犬', 'dog'),
  ('柯基', '威尔士柯基犬', 'dog'),
  ('welsh corgi', '威尔士柯基犬', 'dog'),
  ('corgi', '威尔士柯基犬', 'dog'),
  ('法国斗牛犬', '法国斗牛犬', 'dog'),
  ('法斗', '法国斗牛犬', 'dog'),
  ('french bulldog', '法国斗牛犬', 'dog'),
  ('英国斗牛犬', '英国斗牛犬', 'dog'),
  ('英斗', '英国斗牛犬', 'dog'),
  ('english bulldog', '英国斗牛犬', 'dog'),
  ('哈士奇', '哈士奇', 'dog'),
  ('二哈', '哈士奇', 'dog'),
  ('siberian husky', '哈士奇', 'dog'),
  ('阿拉斯加雪橇犬', '阿拉斯加雪橇犬', 'dog'),
  ('阿拉斯加', '阿拉斯加雪橇犬', 'dog'),
  ('alaskan malamute', '阿拉斯加雪橇犬', 'dog'),
  ('萨摩耶犬', '萨摩耶犬', 'dog'),
  ('萨摩耶', '萨摩耶犬', 'dog'),
  ('samoyed', '萨摩耶犬', 'dog'),
  ('边境牧羊犬', '边境牧羊犬', 'dog'),
  ('边牧', '边境牧羊犬', 'dog'),
  ('border collie', '边境牧羊犬', 'dog'),
  ('德国牧羊犬', '德国牧羊犬', 'dog'),
  ('德牧', '德国牧羊犬', 'dog'),
  ('german shepherd', '德国牧羊犬', 'dog'),
  ('杜宾犬', '杜宾犬', 'dog'),
  ('杜宾', '杜宾犬', 'dog'),
  ('doberman', '杜宾犬', 'dog'),
  ('罗威纳犬', '罗威纳犬', 'dog'),
  ('罗威纳', '罗威纳犬', 'dog'),
  ('rottweiler', '罗威纳犬', 'dog'),
  ('大白熊犬', '大白熊犬', 'dog'),
  ('great pyrenees', '大白熊犬', 'dog'),
  ('圣伯纳犬', '圣伯纳犬', 'dog'),
  ('圣伯纳', '圣伯纳犬', 'dog'),
  ('saint bernard', '圣伯纳犬', 'dog'),
  ('大丹犬', '大丹犬', 'dog'),
  ('great dane', '大丹犬', 'dog'),
  ('斑点狗', '斑点狗', 'dog'),
  ('大麦町', '斑点狗', 'dog'),
  ('dalmatian', '斑点狗', 'dog'),
  ('腊肠犬', '腊肠犬', 'dog'),
  ('腊肠', '腊肠犬', 'dog'),
  ('dachshund', '腊肠犬', 'dog'),
  ('约克夏梗', '约克夏梗', 'dog'),
  ('约克夏', '约克夏梗', 'dog'),
  ('yorkshire terrier', '约克夏梗', 'dog'),
  ('雪纳瑞', '雪纳瑞', 'dog'),
  ('schnauzer', '雪纳瑞', 'dog'),
  ('西高地白梗', '西高地白梗', 'dog'),
  ('west highland white terrier', '西高地白梗', 'dog'),
  ('马尔济斯犬', '马尔济斯犬', 'dog'),
  ('马尔济斯', '马尔济斯犬', 'dog'),
  ('maltese', '马尔济斯犬', 'dog'),
  ('吉娃娃', '吉娃娃', 'dog'),
  ('chihuahua', '吉娃娃', 'dog'),
  ('比格犬', '比格犬', 'dog'),
  ('米格鲁', '比格犬', 'dog'),
  ('beagle', '比格犬', 'dog'),
  ('可卡犬', '可卡犬', 'dog'),
  ('cocker spaniel', '可卡犬', 'dog'),
  ('查理王小猎犬', '查理王小猎犬', 'dog'),
  ('cavalier king charles spaniel', '查理王小猎犬', 'dog'),
  ('澳大利亚牧羊犬', '澳大利亚牧羊犬', 'dog'),
  ('澳牧', '澳大利亚牧羊犬', 'dog'),
  ('australian shepherd', '澳大利亚牧羊犬', 'dog'),
  ('澳大利亚牧牛犬', '澳大利亚牧牛犬', 'dog'),
  ('澳牛', '澳大利亚牧牛犬', 'dog'),
  ('australian cattle dog', '澳大利亚牧牛犬', 'dog'),
  ('杰克罗素梗', '杰克罗素梗', 'dog'),
  ('jack russell terrier', '杰克罗素梗', 'dog'),
  ('斗牛梗', '斗牛梗', 'dog'),
  ('bull terrier', '斗牛梗', 'dog'),
  ('史宾格猎犬', '史宾格猎犬', 'dog'),
  ('english springer spaniel', '史宾格猎犬', 'dog'),
  ('魏玛犬', '魏玛犬', 'dog'),
  ('weimaraner', '魏玛犬', 'dog'),

  -- ── Dog: catch-all for mixed / unknown ──
  ('串串', '串串', 'dog'),
  ('混血犬', '串串', 'dog'),
  ('mixed breed', '串串', 'dog'),
  ('mutt', '串串', 'dog'),

  -- ── Other species ──
  ('米克斯', '米克斯', 'other'),
  ('mixed', '米克斯', 'other'),
  ('混血', '米克斯', 'other'),
  ('其他', '米克斯', 'other')
ON CONFLICT (alias) DO NOTHING;

-- Refresh the breed_product_stats materialized view so existing aggregations
-- pick up the new canonical names. Safe to call even if the view is empty.
SELECT public.refresh_breed_stats();
